// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	xdpmonitorMapPktCount    = "pkt_count"
	xdpmonitorProgXdpMonitor = "xdp_monitor"
)

// loadXdpmonitor returns the embedded CollectionSpec for xdpmonitor.
func loadXdpmonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpmonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdpmonitor: %w", err)
	}

	return spec, err
}

// loadXdpmonitorObjects loads xdpmonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdpmonitorObjects
//	*xdpmonitorPrograms
//	*xdpmonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdpmonitorObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdpmonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdpmonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpmonitorSpecs struct {
	xdpmonitorProgramSpecs
	xdpmonitorMapSpecs
	xdpmonitorVariableSpecs
}

// xdpmonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpmonitorProgramSpecs struct {
	XdpMonitor *ebpf.ProgramSpec `ebpf:"xdp_monitor"`
}

// xdpmonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpmonitorMapSpecs struct {
	PktCount *ebpf.MapSpec `ebpf:"pkt_count"`
}

// xdpmonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpmonitorVariableSpecs struct {
}

// xdpmonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdpmonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpmonitorObjects struct {
	xdpmonitorPrograms
	xdpmonitorMaps
	xdpmonitorVariables
}

func (o *xdpmonitorObjects) Close() error {
	return _XdpmonitorClose(
		&o.xdpmonitorPrograms,
		&o.xdpmonitorMaps,
	)
}

// xdpmonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdpmonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpmonitorMaps struct {
	PktCount *ebpf.Map `ebpf:"pkt_count"`
}

func (m *xdpmonitorMaps) Close() error {
	return _XdpmonitorClose(
		m.PktCount,
	)
}

// xdpmonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdpmonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpmonitorVariables struct {
}

// xdpmonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdpmonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpmonitorPrograms struct {
	XdpMonitor *ebpf.Program `ebpf:"xdp_monitor"`
}

func (p *xdpmonitorPrograms) Close() error {
	return _XdpmonitorClose(
		p.XdpMonitor,
	)
}

func _XdpmonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpmonitor_bpfeb.o
var _XdpmonitorBytes []byte
